namespace: kong-cp
resources:
- ../base
- postgresql
nameSuffix: -cp

patches:
  - target:
      kind: RoleBinding
      name: kong-to-secrets
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: kong-cp
  - target:
      kind: Application
      name: kong
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: kong
        namespace: openshift-gitops
        annotations:
          argocd.argoproj.io/sync-wave: "3"
      spec:
        destination:
          namespace: kong-cp
        source:
          helm:
            values: |
              ingressController:
                enabled: true
                installCRDs: false
                image:
                  repository: kong/kubernetes-ingress-controller
                  tag: 2.3-redhat
              image:
                repository: kong/kong-gateway
                tag: 2.8
              env:
                database: postgres
                role: control_plane
                cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
                cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
                pg_user: kong
                pg_password: kong123
                pg_host: postgresql
              cluster:
                enabled: true
                type: LoadBalancer
                tls:
                  enabled: true
                  servicePort: 8005
                  containerPort: 8005
              clustertelemetry:
                enabled: true
                type: LoadBalancer
                tls:
                  enabled: true
                  servicePort: 8006
                  containerPort: 8006
              proxy:
                enabled: true
                type: ClusterIP
              secretVolumes: 
                - kong-cluster-cert
              admin:
                enabled: true
                type: ClusterIP
                http:
                  enabled: true
              enterprise:
                enabled: true
                license_secret: kong-enterprise-license
                portal:
                  enabled: false
                rbac:
                  enabled: false
                smtp:
                  enabled: false
              manager:
                enabled: true
                type: ClusterIP
