apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - deploymentconfig.yaml
  - service.yaml
secretGenerator:
  - name: postgresql
    type: Opaque
    envs: 
     - postgres.properties